# Site wide configuration

title: Jerome Toole
description: Photography and Photo Stories 
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://photos.jerometoole.co.uk
imagepath: /images

# Jekyll configuration

sass:
    sass_dir: _sass
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Jerome Toole
  email: jerome@jerometoole.co.uk
  twitter: jamrone
  google:
    ad-client: 
    ad-slot: 
  bio: I take pictures and sometimes they see the light of day.
  avatar: jjjrome.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "serve.sh"]

environment: production
