# Site wide configuration

title: Jerome Toole
description: Photography and Photo Stories 
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: 

# Jekyll configuration

sass:
    sass_dir: _sass
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Jerome Toole
  email: jerometoole@gmail.com
  twitter: jamrone
  google:
    ad-client: 
    ad-slot: 
  bio: I do a lot of things but one I particularly love is making images. Capturing scenes and seeing them evolve and refine through the editing process is constantly fascinating to me. Sometimes the pictures tell a story and other times I'd rather they just sat there to be soaked up.
  avatar: jjjrome.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
